In [14]:
class Emp:
    count=0 
    emps=[] 
    def __init__(self,name,family,salary,dept):
        self.name=name
        self.family=family
        self.salary=salary
        self.dept=dept
        Emp.count=Emp.count+1 
        Emp.emps.append(self) 
        

    def average_salary(self):
        return sum(emp.salary for emp in Emp.emps) / Emp.count
    
class Fulltime_Emp(Emp):
        pass
    

#creating instances for above classes 
emp1=Emp("Sai Prakash","Podapati",9999,"CS")
emp2=Emp("ASP",".net",8888,"CS")
full_time_emp = Fulltime_Emp("Uma", "Bankari", 9998, "Managment")


#Accessing the classes using instances 
print(emp1.average_salary())
print(emp2.average_salary())
print(full_time_emp.average_salary())


9628.333333333334
9628.333333333334
9628.333333333334


In [8]:
import numpy as np
import numpy as np 

sampl=np.random.uniform(low=1,high=20,size=20) 
reshape_arr=sampl.reshape((4,5)) 
print(reshape_arr)
np.where(reshape_arr== np.max(reshape_arr, axis=1, keepdims=True), 0, reshape_arr)


[[12.86318339  1.49569304  3.8422182  12.45086312 13.59239865]
 [11.32312672  3.44901832  8.06154891 17.84729258  5.07941713]
 [ 3.90739782 19.67398355  9.58965686  9.10727612 19.3118025 ]
 [13.56850439 16.08267558  2.56828432  7.4763154   7.95323708]]


array([[12.86318339,  1.49569304,  3.8422182 , 12.45086312,  0.        ],
       [11.32312672,  3.44901832,  8.06154891,  0.        ,  5.07941713],
       [ 3.90739782,  0.        ,  9.58965686,  9.10727612, 19.3118025 ],
       [13.56850439,  0.        ,  2.56828432,  7.4763154 ,  7.95323708]])